development:
  adapter: mysql2
  encoding: utf8
  # host: eu-cdbr-west-02.cleardb.net
  database: order_food
  pool: 2
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  # host: eu-cdbr-west-02.cleardb.net
  database: order_food
  pool: 2
  username: root
  password: 